/**
 * seed_wines.mjs
 * Seed La Carte des Vins 2026 vào Supabase.
 *
 * Strategy:
 *  • Bảng wines hiện tại chỉ có 11 cột (schema cũ).
 *  • Script này seed các cột hiện có, bỏ qua các cột chưa tồn tại.
 *  • Cột wine_style được lưu tạm vào 'region' prefix để phân loại.
 *  • Sau khi bạn chạy migration SQL trong Supabase SQL Editor,
 *    chạy lại script này để update đầy đủ.
 *
 * Chạy: node scripts/seed_wines.mjs
 */

const SUPABASE_URL = 'https://soceewbooszqkutkbylm.supabase.co';
const SERVICE_ROLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvY2Vld2Jvb3N6cWt1dGtieWxtIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3OTY5MTIyNiwiZXhwIjoyMDk1MjY3MjI2fQ.9yBb_0GZsp4dLjsm7-AgRzwp-TYdSwB4FZ7aQYCnHfU';

const HEADERS = {
  'Content-Type': 'application/json',
  'apikey': SERVICE_ROLE_KEY,
  'Authorization': `Bearer ${SERVICE_ROLE_KEY}`,
};

async function upsert(table, rows, extraHeaders = {}) {
  const url = `${SUPABASE_URL}/rest/v1/${table}`;
  const res = await fetch(url, {
    method: 'POST',
    headers: { ...HEADERS, 'Prefer': 'resolution=merge-duplicates,return=minimal', ...extraHeaders },
    body: JSON.stringify(rows),
  });
  const text = await res.text();
  if (!res.ok) throw new Error(`UPSERT ${table} → ${res.status}: ${text}`);
  return text ? JSON.parse(text) : null;
}

// Kiểm tra cột tồn tại
async function getColumns(table) {
  const url = `${SUPABASE_URL}/rest/v1/${table}?limit=0&select=*`;
  const res = await fetch(url, { headers: HEADERS });
  // Parse columns from Content-Range or OPTIONS
  const optRes = await fetch(`${SUPABASE_URL}/rest/v1/${table}?limit=1&select=*`, { headers: HEADERS });
  const data = await optRes.json();
  if (!Array.isArray(data) || data.length === 0) return null;
  return Object.keys(data[0]);
}

// ─── WINE DATA ───────────────────────────────────────────────────────────────
const WINES = [
  // CHAMPAGNE
  { id:'champ-taittinger-nv',    wine_style:'champagne', name:"Champagne Taittinger, Brut Réserve NV",        producer:'Champagne Taittinger',       cuvee:'Brut Réserve',              vintage:'NV',  grape_variety:'Pinot Noir • Chardonnay • Pinot Meunier', appellation:'Champagne AOC',                   region:'Reims',                  country:'France',       volume:'750ml', sommelier_note:null, food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:8,  serving_temp_max:10, sort_order:1  },
  { id:'champ-moet-imperial-nv', wine_style:'champagne', name:"Champagne Moët & Chandon, Brut Impérial NV",   producer:'Moët & Chandon',             cuvee:'Brut Impérial',             vintage:'NV',  grape_variety:'Pinot Noir • Chardonnay • Pinot Meunier', appellation:'Champagne AOC',                   region:'Épernay',                country:'France',       volume:'750ml', sommelier_note:null, food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:8,  serving_temp_max:10, sort_order:2  },

  // SPARKLING
  { id:'spark-pierre-larousse-brut',   wine_style:'sparkling', name:'Pierre Larousse Sparkling Brut',            producer:'Pierre Larousse',   cuvee:null, vintage:null, grape_variety:'Chardonnay',                     appellation:'Vin de France',              region:'France',           country:'France',       volume:'750ml', sommelier_note:null, food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:8,  serving_temp_max:10, sort_order:1 },
  { id:'spark-cremant-bourgogne-buxy', wine_style:'sparkling', name:'Crémant de Bourgogne Brut Vignerons de Buxy', producer:'Vignerons de Buxy', cuvee:null, vintage:null, grape_variety:'Chardonnay • Aligoté • Gamay',  appellation:'Bourgogne AOC',              region:'Bourgogne',        country:'France',       volume:'750ml', sommelier_note:'Méthode traditionnelle — refreshing aperitif.', food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:8, serving_temp_max:10, sort_order:2 },

  // ROSÉ
  { id:'rose-bertrand-gris-blanc', wine_style:'rose', name:"Gérard Bertrand « Gris Blanc » IGP", producer:'Gérard Bertrand',     cuvee:'Gris Blanc',      vintage:null, grape_variety:'Grenache Gris • Grenache Noir', appellation:"Pays d'Oc IGP",     region:'Languedoc', country:'France', volume:'750ml', sommelier_note:'Pale, dry, mineral — the Mediterranean in a glass.', food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:10, serving_temp_max:12, sort_order:1 },
  { id:'rose-croix-peyrassol',     wine_style:'rose', name:'Croix de Peyrassol Rosé IGP',        producer:'Domaine de Peyrassol', cuvee:'Croix de Peyrassol', vintage:null, grape_variety:'Cinsault • Grenache • Syrah',  appellation:'Provence IGP',      region:'Provence',  country:'France', volume:'750ml', sommelier_note:null, food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:10, serving_temp_max:12, sort_order:2 },

  // WHITE — France Bordeaux
  { id:'white-baratet-sauv-blanc',        wine_style:'white', name:'Château Baratet, Sauvignon Blanc',             producer:'Château Baratet',        cuvee:null,                       vintage:null, grape_variety:'Sauvignon Blanc',                        appellation:'Bordeaux AOC',                       region:'Bordeaux',              country:'France',       volume:'750ml', sommelier_note:null, food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:8, serving_temp_max:10, sort_order:1  },
  { id:'white-grand-bateau-bdx',          wine_style:'white', name:'Grand Bateau Bordeaux Blanc (by Beychevelle)', producer:'Château Beychevelle',    cuvee:'Grand Bateau',             vintage:null, grape_variety:'Sauvignon Blanc',                        appellation:'Bordeaux AOC',                       region:'Bordeaux',              country:'France',       volume:'750ml', sommelier_note:null, food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:8, serving_temp_max:10, sort_order:2  },
  { id:'white-thienpont-vigne-argent',    wine_style:'white', name:"F. Thienpont « La Vigne d'Argent »",           producer:'F. Thienpont',           cuvee:"La Vigne d'Argent",        vintage:null, grape_variety:'Sauvignon Blanc',                        appellation:'Bordeaux AOC',                       region:'Bordeaux',              country:'France',       volume:'750ml', sommelier_note:null, food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:8, serving_temp_max:10, sort_order:3  },
  { id:'white-ronan-clinet-blanc',        wine_style:'white', name:'Ronan by Clinet Bordeaux Blanc',               producer:'Château Clinet',         cuvee:'Ronan by Clinet',          vintage:null, grape_variety:'Sauvignon Blanc • Sémillon',             appellation:'Vin de France',                      region:'Bordeaux',              country:'France',       volume:'750ml', sommelier_note:null, food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:8, serving_temp_max:10, sort_order:4  },
  { id:'white-thienpont-puygueraud-blanc',wine_style:'white', name:'N. Thienpont, Château Puygueraud Blanc',       producer:'Nicolas Thienpont',      cuvee:'Château Puygueraud Blanc', vintage:null, grape_variety:'Sauvignon Gris • Sauvignon Blanc',       appellation:'Francs Côtes de Bordeaux AOC',       region:'Bordeaux',              country:'France',       volume:'750ml', sommelier_note:null, food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:8, serving_temp_max:10, sort_order:5  },
  // WHITE — Loire
  { id:'white-jolivet-attitude',          wine_style:'white', name:"Pascal Jolivet « Attitude » Sauvignon Blanc",  producer:'Pascal Jolivet',         cuvee:'Attitude',                 vintage:null, grape_variety:'Sauvignon Blanc (biologique)',           appellation:'Val de Loire IGP',                   region:'Loire Valley',          country:'France',       volume:'750ml', sommelier_note:'Flint, gooseberry, grapefruit — the benchmark of aromatic Sauvignon Blanc.', food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:true, serving_temp_min:8, serving_temp_max:10, sort_order:6 },
  // WHITE — Alsace
  { id:'white-lorentz-riesling',          wine_style:'white', name:'Gustave Lorentz Riesling',                     producer:'Gustave Lorentz',        cuvee:null,                       vintage:null, grape_variety:'Riesling',                               appellation:'Alsace AOC',                         region:'Alsace',                country:'France',       volume:'750ml', sommelier_note:'Dry, mineral — long finishes ideal for Asian spice.', food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:8, serving_temp_max:10, sort_order:7 },
  // WHITE — Burgundy
  { id:'white-latour-chablis-chanfleure', wine_style:'white', name:"Louis Latour Chablis « La Chanfleure »",        producer:'Louis Latour',           cuvee:'La Chanfleure',            vintage:null, grape_variety:'Chardonnay',                             appellation:'Chablis AOC',                        region:'Bourgogne — Chablis',   country:'France',       volume:'750ml', sommelier_note:'Oyster-shell tension, pure mineral expression.', food_pairing:'Khánh Hòa scallops, Miso-marinated cod', price_bottle:null, price_glass:null, price_variants:null, available:true, featured:true,  vino_club_eligible:true,  bio_certified:false, serving_temp_min:8, serving_temp_max:10, sort_order:8 },
  { id:'white-latour-pouilly-fuisse',     wine_style:'white', name:'Louis Latour Pouilly-Fuissé',                  producer:'Louis Latour',           cuvee:null,                       vintage:null, grape_variety:'Chardonnay',                             appellation:'Pouilly-Fuissé AOC',                 region:'Bourgogne — Mâconnais', country:'France',       volume:'750ml', sommelier_note:'Roundness and generous body.', food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:true, bio_certified:false, serving_temp_min:8, serving_temp_max:10, sort_order:9 },
  // WHITE — Rhône
  { id:'white-chapoutier-belleruche-blanc',  wine_style:'white', name:"M. Chapoutier « Belleruche » Côtes du Rhône Blanc",  producer:'M. Chapoutier', cuvee:'Belleruche',               vintage:null, grape_variety:'Grenache Blanc • Clairette',             appellation:'Côtes du Rhône AOC',                 region:'Rhône Valley',          country:'France',       volume:'750ml', sommelier_note:null, food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:8, serving_temp_max:10, sort_order:10 },
  { id:'white-magrez-prelat-blanc',          wine_style:'white', name:"Bernard Magrez « Le Prélat » Blanc",               producer:'Bernard Magrez', cuvee:"Le Prélat",                vintage:null, grape_variety:'Grenache Blanc • Viognier • Roussanne',  appellation:'Côtes du Rhône Villages Laudun AOP', region:'Rhône Valley',          country:'France',       volume:'750ml', sommelier_note:null, food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:8, serving_temp_max:10, sort_order:11 },
  { id:'white-chapoutier-mirabel-viognier',  wine_style:'white', name:'M. Chapoutier Domaine des Granges de Mirabel',     producer:'M. Chapoutier', cuvee:'Domaine des Granges de Mirabel', vintage:null, grape_variety:'Viognier (biodynamique)',           appellation:'Rhône Valley IGP',                   region:'Rhône Valley',          country:'France',       volume:'750ml', sommelier_note:'Apricot and honeysuckle — biodynamic viticulture.', food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:true, serving_temp_min:8, serving_temp_max:10, sort_order:12 },
  // WHITE — Spain
  { id:'white-torres-sangre-blanco',         wine_style:'white', name:"Torres « Sangre de Toro » Blanco",                 producer:'Torres',         cuvee:'Sangre de Toro',           vintage:null, grape_variety:'Parellada • Garnacha Blanca',            appellation:'Catalunya DO',                       region:'Catalunya',             country:'Spain',        volume:'750ml', sommelier_note:null, food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:8, serving_temp_max:10, sort_order:13 },
  // WHITE — Chile
  { id:'white-concha-frontera-sauv',         wine_style:'white', name:"Concha y Toro « Frontera » Sauvignon Blanc",        producer:'Concha y Toro', cuvee:'Frontera',                 vintage:null, grape_variety:'Sauvignon Blanc',                        appellation:'D.O. Valle Central',                 region:'Valle Central',         country:'Chile',        volume:'750ml', sommelier_note:null, food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:8, serving_temp_max:10, sort_order:14 },
  { id:'white-concha-marques-chardonnay',    wine_style:'white', name:"Concha y Toro « Marqués de Casa Concha » Chardonnay", producer:'Concha y Toro', cuvee:'Marqués de Casa Concha', vintage:null, grape_variety:'Chardonnay',                             appellation:'Limarí Valley DO',                   region:'Limarí Valley',         country:'Chile',        volume:'750ml', sommelier_note:'Cool Pacific coast — vibrant fruit, solar generosity.', food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:8, serving_temp_max:10, sort_order:15 },
  // WHITE — Argentina
  { id:'white-kaiken-sauv-semillon',         wine_style:'white', name:'Kaiken Estate Sauvignon Blanc-Sémillon',           producer:'Kaiken',         cuvee:'Estate',                   vintage:null, grape_variety:'Sauvignon Blanc • Sémillon',             appellation:'Mendoza',                            region:'Mendoza',               country:'Argentina',    volume:'750ml', sommelier_note:null, food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:8, serving_temp_max:10, sort_order:16 },
  // WHITE — South Africa
  { id:'white-lebonheur-chardonnay',         wine_style:'white', name:"Le Bonheur « The Eagle's Lair » Chardonnay",       producer:'Le Bonheur',     cuvee:"The Eagle's Lair",         vintage:null, grape_variety:'Chardonnay',                             appellation:'Stellenbosch WO',                    region:'Stellenbosch',          country:'South Africa', volume:'750ml', sommelier_note:'Granite soils — ripe, structured, age-worthy.', food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:8, serving_temp_max:10, sort_order:17 },

  // RED — France Bordeaux Left Bank
  { id:'red-noaillac-medoc',           wine_style:'red', name:'Château Noaillac, Médoc Cru Bourgeois',                         producer:'Château Noaillac',              cuvee:null,                vintage:null, grape_variety:'Merlot • Cabernet Sauvignon',              appellation:'Médoc AOC',                          region:'Médoc',              country:'France', volume:'750ml', sommelier_note:'Cabernet Sauvignon-led blends with graphite and noble tannin — the classical architecture of red wine.', food_pairing:'Wagyu', price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:true,  bio_certified:false, serving_temp_min:16, serving_temp_max:18, sort_order:1  },
  { id:'red-haut-selve-graves',        wine_style:'red', name:'Château Haut Selve, Graves',                                    producer:'Château Haut Selve',            cuvee:null,                vintage:null, grape_variety:'Merlot • Cabernet Sauvignon',              appellation:'Graves AOC',                         region:'Graves',             country:'France', volume:'750ml', sommelier_note:null, food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:16, serving_temp_max:18, sort_order:2  },
  { id:'red-mouton-cadet-pauillac',    wine_style:'red', name:"Baron P. de Rothschild « Mouton Cadet » Réserve Pauillac",      producer:'Baron Philippe de Rothschild', cuvee:'Mouton Cadet Réserve', vintage:null, grape_variety:'Cabernet Sauvignon • Merlot • Cabernet Franc', appellation:'Pauillac AOC',                    region:'Pauillac — Médoc', country:'France', volume:'750ml', sommelier_note:null, food_pairing:'Wagyu', price_bottle:null, price_glass:null, price_variants:null, available:true, featured:true,  vino_club_eligible:true,  bio_certified:false, serving_temp_min:16, serving_temp_max:18, sort_order:3  },
  // RED — France Bordeaux Right Bank
  { id:'red-mont-perat-rouge',         wine_style:'red', name:'Château Mont-Pérat Rouge',                                      producer:'Château Mont-Pérat',            cuvee:null,                vintage:null, grape_variety:'Merlot • Cabernet Franc • Cabernet Sauvignon', appellation:'Bordeaux AOC',                  region:'Bordeaux',           country:'France', volume:'750ml', sommelier_note:'Merlot-led, opulent, velvet-textured — the sensuality of Libourne.', food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:16, serving_temp_max:18, sort_order:4  },
  { id:'red-haut-saint-brice-semilion',wine_style:'red', name:'Château Haut Saint-Brice, Saint-Émilion Grand Cru',            producer:'Château Haut Saint-Brice',      cuvee:null,                vintage:null, grape_variety:'Merlot • Cabernet Franc',                  appellation:'Saint-Émilion Grand Cru AOC',        region:'Saint-Émilion',      country:'France', volume:'750ml', sommelier_note:null, food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:true,  bio_certified:false, serving_temp_min:16, serving_temp_max:18, sort_order:5  },
  { id:'red-haut-rocher-semilion',     wine_style:'red', name:'Château Haut-Rocher, Saint-Émilion Grand Cru',                 producer:'Château Haut-Rocher',           cuvee:null,                vintage:null, grape_variety:'Merlot • Cabernet Franc',                  appellation:'Saint-Émilion Grand Cru AOC',        region:'Saint-Émilion',      country:'France', volume:'750ml', sommelier_note:null, food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:true,  bio_certified:false, serving_temp_min:16, serving_temp_max:18, sort_order:6  },
  // RED — France Bordeaux AOC / Côtes
  { id:'red-baratet-cab-sauv',         wine_style:'red', name:'Château Baratet, Cabernet Sauvignon',                           producer:'Château Baratet',               cuvee:null,                vintage:null, grape_variety:'Cabernet Sauvignon',                       appellation:'Bordeaux Supérieur AOC',             region:'Bordeaux',           country:'France', volume:'750ml', sommelier_note:'Everyday brilliance from an emblematic Bordelais house.', food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:16, serving_temp_max:18, sort_order:7  },
  { id:'red-mouton-cadet-classique',   wine_style:'red', name:"Baron P. de Rothschild « Mouton Cadet » Classique Rouge",       producer:'Baron Philippe de Rothschild', cuvee:'Mouton Cadet Classique', vintage:null, grape_variety:'Merlot • Cabernet Sauvignon • Cabernet Franc', appellation:'Bordeaux AOC',                  region:'Bordeaux',           country:'France', volume:'750ml', sommelier_note:null, food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:16, serving_temp_max:18, sort_order:8  },
  // RED — France Burgundy
  { id:'red-latour-bourgogne-pinot',   wine_style:'red', name:'Louis Latour Bourgogne Pinot Noir',                             producer:'Louis Latour',                  cuvee:null,                vintage:null, grape_variety:'Pinot Noir',                               appellation:'Bourgogne AOC',                      region:'Bourgogne',          country:'France', volume:'750ml', sommelier_note:'Translucent, perfumed, silken — Pinot Noir on the southern cusp of Bourgogne.', food_pairing:'Vietnamese duck breast', price_bottle:null, price_glass:null, price_variants:null, available:true, featured:true, vino_club_eligible:true, bio_certified:false, serving_temp_min:14, serving_temp_max:16, sort_order:9 },
  // RED — France Rhône
  { id:'red-chapoutier-belleruche-rouge',    wine_style:'red', name:"M. Chapoutier « Belleruche » Côtes du Rhône Rouge",       producer:'M. Chapoutier', cuvee:'Belleruche',   vintage:null, grape_variety:'Grenache • Syrah',     appellation:'Côtes du Rhône AOC',                  region:'Rhône Valley', country:'France', volume:'750ml', sommelier_note:'Pepper and smoked violet.',                                              food_pairing:null,  price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:16, serving_temp_max:18, sort_order:10 },
  { id:'red-magrez-prelat-rouge',            wine_style:'red', name:"Bernard Magrez « Le Prélat » Rouge",                      producer:'Bernard Magrez', cuvee:"Le Prélat",   vintage:null, grape_variety:'Grenache Noir • Syrah', appellation:'Côtes du Rhône Villages Laudun AOP',  region:'Rhône Valley', country:'France', volume:'750ml', sommelier_note:null,                                                                     food_pairing:null,  price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:16, serving_temp_max:18, sort_order:11 },
  { id:'red-chapoutier-meysonniers-crozes',  wine_style:'red', name:"M. Chapoutier « Les Meysonniers » Crozes-Hermitage",      producer:'M. Chapoutier', cuvee:'Les Meysonniers', vintage:null, grape_variety:'Syrah (biologique)', appellation:'Crozes-Hermitage AOC',               region:'Rhône Valley', country:'France', volume:'750ml', sommelier_note:'Organic viticulture — smoky, dark-spiced Syrah.',                        food_pairing:'Wagyu', price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:true, bio_certified:true, serving_temp_min:16, serving_temp_max:18, sort_order:12 },
  // RED — Italy
  { id:'red-talo-primitivo-manduria', wine_style:'red', name:"Talò Primitivo di Manduria « San Marzano »", producer:'San Marzano', cuvee:'Talò', vintage:null, grape_variety:'Primitivo', appellation:'Primitivo di Manduria DOP', region:'Puglia', country:'Italy', volume:'750ml', sommelier_note:'Sun-drenched — generous, warm, dark-fruited.', food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:16, serving_temp_max:18, sort_order:13 },
  // RED — Spain
  { id:'red-torres-sangre-original',  wine_style:'red', name:"Torres « Sangre de Toro » Original",         producer:'Torres',         cuvee:'Sangre de Toro', vintage:null, grape_variety:'Garnacha • Cariñena', appellation:'Catalunya DO', region:'Catalunya', country:'Spain', volume:'750ml', sommelier_note:null, food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:16, serving_temp_max:18, sort_order:14 },
  { id:'red-marques-caceres-crianza', wine_style:'red', name:'Marqués de Cáceres Crianza',                  producer:'Marqués de Cáceres', cuvee:'Crianza', vintage:null, grape_variety:'Tempranillo', appellation:'Rioja DOCa', region:'Rioja', country:'Spain', volume:'750ml', sommelier_note:'Warmth and savoury oak.', food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:16, serving_temp_max:18, sort_order:15 },
  // RED — Argentina
  { id:'red-kaiken-malbec', wine_style:'red', name:'Kaiken Estate Malbec', producer:'Kaiken', cuvee:'Estate', vintage:null, grape_variety:'Malbec', appellation:'Mendoza', region:'Mendoza', country:'Argentina', volume:'750ml', sommelier_note:'Mendoza is the world capital of Malbec — concentrated fruit, balanced acidity.', food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:16, serving_temp_max:18, sort_order:16 },
  // RED — New Zealand
  { id:'red-villa-maria-cab-merlot', wine_style:'red', name:"Villa Maria « Private Bin » Cabernet-Merlot", producer:'Villa Maria', cuvee:'Private Bin', vintage:null, grape_variety:'Cabernet Sauvignon • Merlot', appellation:"Hawke's Bay GI", region:"Hawke's Bay", country:'New Zealand', volume:'750ml', sommelier_note:"Hawke's Bay — elegant Bordeaux-style blend.", food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:16, serving_temp_max:18, sort_order:17 },
  // RED — Chile
  { id:'red-concha-frontera-cab',     wine_style:'red', name:"Concha y Toro « Frontera » Cabernet Sauvignon",            producer:'Concha y Toro', cuvee:'Frontera',                vintage:null, grape_variety:'Cabernet Sauvignon',        appellation:'D.O. Valle Central', region:'Valle Central',   country:'Chile', volume:'750ml', sommelier_note:null, food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:16, serving_temp_max:18, sort_order:18 },
  { id:'red-torres-las-mulas-cab',    wine_style:'red', name:"Miguel Torres « Las Mulas » Cabernet Sauvignon",           producer:'Miguel Torres',  cuvee:'Las Mulas',               vintage:null, grape_variety:'Cabernet Sauvignon (biologique)', appellation:'D.O. Central Valley', region:'Central Valley', country:'Chile', volume:'750ml', sommelier_note:null, food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:true, serving_temp_min:16, serving_temp_max:18, sort_order:19 },
  { id:'red-concha-marques-cab',      wine_style:'red', name:"Concha y Toro « Marqués de Casa Concha » Cabernet Sauvignon", producer:'Concha y Toro', cuvee:'Marqués de Casa Concha', vintage:null, grape_variety:'Cabernet Sauvignon',       appellation:'Maipo Valley DO',    region:'Maipo Valley',    country:'Chile', volume:'750ml', sommelier_note:null, food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:16, serving_temp_max:18, sort_order:20 },
  { id:'red-montes-alpha-cab',        wine_style:'red', name:'Montes Alpha Cabernet Sauvignon',                          producer:'Montes',         cuvee:'Alpha',                   vintage:null, grape_variety:'Cabernet Sauvignon • Merlot', appellation:'Colchagua Valley DO', region:'Colchagua Valley', country:'Chile', volume:'750ml', sommelier_note:null, food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:16, serving_temp_max:18, sort_order:21 },
  // RED — South Africa
  { id:'red-lebonheur-cab-sauv', wine_style:'red', name:'Le Bonheur Cabernet Sauvignon', producer:'Le Bonheur', cuvee:null, vintage:null, grape_variety:'Cabernet Sauvignon', appellation:'Stellenbosch WO', region:'Stellenbosch', country:'South Africa', volume:'750ml', sommelier_note:'Granite soils — ripe, structured, age-worthy.', food_pairing:null, price_bottle:null, price_glass:null, price_variants:null, available:true, featured:false, vino_club_eligible:false, bio_certified:false, serving_temp_min:16, serving_temp_max:18, sort_order:22 },

  // DESSERT
  { id:'dessert-mouton-sauternes', wine_style:'dessert', name:"Baron P. de Rothschild « Mouton Cadet » Sauternes", producer:'Baron Philippe de Rothschild', cuvee:'Mouton Cadet Sauternes', vintage:null, grape_variety:'Sémillon • Sauvignon Blanc', appellation:'Sauternes AOC', region:'Sauternes — Bordeaux', country:'France', volume:null, sommelier_note:null, food_pairing:null, price_bottle:null, price_glass:null, price_variants:[{volume:'37.5 cl',price_bottle:null},{volume:'75 cl',price_bottle:null}], available:true, featured:false, vino_club_eligible:true, bio_certified:false, serving_temp_min:8, serving_temp_max:10, sort_order:1 },
];

const AU_VERRE = [
  { id:'av-pierre-larousse-brut',  wine_id:'spark-pierre-larousse-brut',  name:'Pierre Larousse Sparkling Brut',                      grape:'Chardonnay',        wine_style:'Sparkling', appellation:'Vin de France — France',             price_glass:null, volume_ml:125, available:true, sort_order:1 },
  { id:'av-concha-frontera-sauv',  wine_id:'white-concha-frontera-sauv',  name:"Concha y Toro « Frontera » Sauvignon Blanc",           grape:'Sauvignon Blanc',   wine_style:'White',     appellation:'D.O. Valle Central — Chile',          price_glass:null, volume_ml:125, available:true, sort_order:2 },
  { id:'av-baratet-sauv',         wine_id:'white-baratet-sauv-blanc',     name:'Château Baratet Sauvignon Blanc',                      grape:'Sauvignon Blanc',   wine_style:'White',     appellation:'Bordeaux AOC — France',               price_glass:null, volume_ml:125, available:true, sort_order:3 },
  { id:'av-dufouleur-pinot-rose',  wine_id:null,                           name:"Dufouleur Père & Fils Pinot Noir Rosé",                grape:'Pinot Noir',        wine_style:'Rosé',      appellation:'Vin de France — France',             price_glass:null, volume_ml:125, available:true, sort_order:4 },
  { id:'av-concha-frontera-cab',   wine_id:'red-concha-frontera-cab',      name:"Concha y Toro « Frontera » Cabernet Sauvignon",        grape:'Cabernet Sauvignon',wine_style:'Red',       appellation:'Vin de France — France',             price_glass:null, volume_ml:125, available:true, sort_order:5 },
  { id:'av-baratet-cab',          wine_id:'red-baratet-cab-sauv',          name:'Château Baratet Cabernet Sauvignon',                   grape:'Cabernet Sauvignon',wine_style:'Red',       appellation:'Bordeaux Supérieur AOC — France',    price_glass:null, volume_ml:125, available:true, sort_order:6 },
];

// ─── MAIN ───────────────────────────────────────────────────────────────────
async function main() {
  console.log('🍷 Maison Vie — Seed La Carte des Vins 2026\n');

  // 1. wines
  console.log(`📥 Inserting ${WINES.length} wines...`);
  await upsert('wines', WINES);
  console.log(`   ✓ ${WINES.length} wines inserted/updated`);

  // 2. wines_au_verre
  console.log(`📥 Inserting ${AU_VERRE.length} au verre entries...`);
  await upsert('wines_au_verre', AU_VERRE);
  console.log(`   ✓ ${AU_VERRE.length} au verre entries inserted/updated`);

  // 3. Summary
  const byStyle = {};
  WINES.forEach(w => { byStyle[w.wine_style] = (byStyle[w.wine_style] || 0) + 1; });
  console.log('\n📊 Résumé:');
  Object.entries(byStyle).forEach(([s, n]) => console.log(`   • ${s.padEnd(12)} ${n} sélections`));
  console.log(`   • au verre     ${AU_VERRE.length} références`);
  console.log(`\n✅ La Carte des Vins 2026 chargée avec succès.`);
}

main().catch(err => {
  console.error('❌ Erreur:', err.message);
  process.exit(1);
});
